/**
 * SpoonacularAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/19/2017
 */

var Configuration = {
    //The base Uri for API calls
    BASEURI : "https://spoonacular-recipe-food-nutrition-v1.p.mashape.com",

    //The Mashape application you want to use for this session.
    //TODO: Replace the XMashapeKey with an appropriate value
    xMashapeKey : "ZMh6WFtGZTmshzeHIQXXkO28zrAmp1O695Yjsn4Y9IePA2s0Nv"
    // xMashapeKey : "721fce4e3ffcc41e0ea3fb0d41534ddc"

};

module.exports = Configuration;
